app/controllers/logs.py
from flask import Blueprint
from flask_login import current_user, login_required
from flask import render_template, redirect, url_for, flash, request, send_file
from app.lib.base.provider import Provider
import time

bp = Blueprint('logs', __name__, url_prefix='/logs')


@bp.route('/', methods=['GET'])
@login_required
def index():
    provider = Provider()
    search = provider.search()
    aliases = provider.aliases()

    results = search.search_from_request(request)
    advanced = int(request.args.get('advanced', 0)) == 1

    return render_template(
        'logs/index.html',
        results=results['results'],
        params=results['params'],
        filters=results['filters'],
        page_url='logs.index',
        advanced=advanced,
        aliases=aliases.get_dict(None if current_user.admin else current_user.id)
    )


@bp.route('/export/', methods=['POST'])
@login_required
def export():
    provider = Provider()
    search = provider.search()
    logs = provider.dns_logs()
    users = provider.users()

    # Prepare names and variables.
    filename = str(int(time.time())) + '.csv'
    download_filename = "snitch_logs_" + filename
    save_results_as = users.get_user_data_path(current_user.id, filename=filename)

    # Perform the search.
    results = search.search_from_request(request, paginate=False, method='get')
    rows = results['results']

    # Export to disk.
    if not logs.save_results_csv(rows, save_results_as, overwrite=True):
        flash('Could not generate CSV file.', 'error')
        return redirect(url_for('logs.index'))

    # And download.
    return send_file(save_results_as, attachment_filename=download_filename, as_attachment=True)

app/templates/logs/index.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-lg">
        <h1 class="mb-5">
            <div>
                <div class="d-inline">Search Logs</div>
                <div style="font-size: 0.4em; top: -16px; left: -6px; position: relative;" class="d-inline">
                    <a href="#" title="" data-container="body" data-toggle="popover" data-placement="right" data-content="Searches use '=' unless you use the '%' operator<br><br>Search for domain 'example.com' will evaluate to &quot;WHERE domain = 'example.com'&quot;<br><br>Search for domain 'example.%' will evaluate to &quot;WHERE domain LIKE 'example.%'&quot;" data-original-title="Search Help"><i class="fas fa-question-circle ml-1"></i></a>
                </div>
            </div>
        </h1>

        <div class="search-form">
            <form action="{{ url_for('logs.index') }}" method="get">
                <input type="hidden" name="advanced" value="1" class="field-advanced">
                <div class="form-group row">
                    <div class="col-lg-6">
                        <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">Domain</span></div>
                            <input type="text" class="form-control" value="{{ params.domain }}" name="domain" placeholder="%.example.com">

                            <div class="input-group-prepend"><span class="input-group-text">Source IP</span></div>
                            <input type="text" class="form-control" value="{{ params.source_ip }}" name="source_ip" placeholder="192.168.%">
                        </div>
                    </div>
                    <div class="col-lg-4 pl-0 ml-0">
                        <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">Type</span></div>
                            <select class="custom-select form-control" name="type">
                                <option value=""></option>
                                {% for type in filters.types %}
                                <option value="{{ type }}" {{ 'selected' if type == params.type }}>{{ type }}</option>
                                {% endfor %}
                            </select>

                            <div class="input-group-prepend"><span class="input-group-text">Matched</span></div>
                            <select class="custom-select" name="matched">
                                <option value="-1" {{ 'selected' if params.matched == -1 }}></option>
                                <option value="0" {{ 'selected' if params.matched == 0 }}>No</option>
                                <option value="1" {{ 'selected' if params.matched == 1 }}>Yes</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg pl-0 ml-0">
                        <button type="submit" class="btn btn-primary btn-block">search</button>
                    </div>
                </div>
                <div class="form-group row search-advanced">
                    <div class="col-lg-5">
                        <div class="row">
                            <div class="col-lg mr-0 pr-0">
                                <div class="input-group date" id="date_from" data-target-input="nearest">
                                    <div class="input-group-prepend"><span class="input-group-text">From</span></div>
                                    <input type="text" class="form-control datetimepicker-input text-right" name="date_from" data-target="#date_from" placeholder="YYYY-MM-DD">
                                    <div class="input-group-append" data-target="#date_from" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg ml-0 pl-0">
                                <div class="input-group date" id="time_from" data-target-input="nearest">
                                    <div class="input-group-prepend"><span class="input-group-text">At</span></div>
                                    <input type="text" class="form-control datetimepicker-input text-right" name="time_from" data-target="#time_from" placeholder="HH:MM">
                                    <div class="input-group-append" data-target="#time_from" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-clock"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg ml-0 pl-0">
                        <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">Forwarded</span></div>
                            <select class="custom-select" name="forwarded">
                                <option value="-1" {{ 'selected' if params.forwarded == -1 }}></option>
                                <option value="0" {{ 'selected' if params.forwarded == 0 }}>No</option>
                                <option value="1" {{ 'selected' if params.forwarded == 1 }}>Yes</option>
                            </select>

                            <div class="input-group-prepend"><span class="input-group-text">Blocked</span></div>
                            <select class="custom-select" name="blocked">
                                <option value="-1" {{ 'selected' if params.blocked == -1 }}></option>
                                <option value="0" {{ 'selected' if params.blocked == 0 }}>No</option>
                                <option value="1" {{ 'selected' if params.blocked == 1 }}>Yes</option>
                            </select>
                        </div>
                    </div>
                    {% if current_user.admin %}
                    <div class="col-lg-3 ml-0 pl-0">
                        <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">User</span></div>
                            <select class="custom-select" name="user_id">
                                <option value="-1"></option>
                                <option value="0" {{ 'selected' if 0 == params.user_id }}>Everyone</option>
                                {% for user_id, username in filters.users.items() %}
                                <option value="{{ user_id }}" {{ 'selected' if user_id == params.user_id }}>{{ username }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    {% endif %}
                </div>
                <div class="form-group row search-advanced">
                    <div class="col-lg-5">
                        <div class="row">
                            <div class="col-lg mr-0 pr-0">
                                <div class="input-group date" id="date_to" data-target-input="nearest">
                                    <div class="input-group-prepend"><span class="input-group-text">To</span></div>
                                    <input type="text" class="form-control datetimepicker-input text-right" name="date_to" data-target="#date_to" placeholder="YYYY-MM-DD">
                                    <div class="input-group-append" data-target="#date_to" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg ml-0 pl-0">
                                <div class="input-group date" id="time_to" data-target-input="nearest">
                                    <div class="input-group-prepend"><span class="input-group-text">At</span></div>
                                    <input type="text" class="form-control datetimepicker-input text-right" name="time_to" data-target="#time_to" placeholder="HH:MM">
                                    <div class="input-group-append" data-target="#time_to" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-clock"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg ml-0 pl-0">
                        <div class="row">
                            <div class="col-lg mr-0">
                                <div class="input-group">
                                    <div class="input-group-prepend"><span class="input-group-text">Tags</span></div>
                                    <select class="custom-select" name="tags" id="tags" multiple="multiple">
                                        {% for tag in filters.tags %}
                                        <option value="{{ tag }}" {{ 'selected' if tag in params.tags }}>{{ tag }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            {% if aliases|length > 0 %}
                            <div class="col-lg ml-0 pl-0">
                                <div class="input-group">
                                    <div class="input-group-prepend"><span class="input-group-text">Alias</span></div>
                                    <select class="custom-select" name="alias">
                                        <option value="-1"></option>
                                        {% for ip, alias in aliases.items() %}
                                        <option value="{{ alias }}" {{ 'selected' if alias == params.alias }}>{{ alias }} - {{ ip }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg text-right">
                        <a href="#" class="text-info toggle-advanced">show advanced search</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% include 'logs/results.html' %}

<script type="text/javascript">
    $(document).ready(function() {
        $('#date_from').datetimepicker({
            format: 'Y-MM-DD',
            date: '{{ params.full_date_from }}'
        });

        $('#date_to').datetimepicker({
            format: 'Y-MM-DD',
            date: '{{ params.full_date_to }}'
        });

        $('#time_from').datetimepicker({
            format: 'HH:mm',
            date: '{{ params.full_date_from }}'
        });

        $('#time_to').datetimepicker({
            format: 'HH:mm',
            date: '{{ params.full_date_to }}'
        });

        $('#tags').select2({
            tags: true
        });

        $('.toggle-advanced').click(function() {
            if ($('.search-advanced').hasClass('hidden')) {
                $(this).text('hide advanced search');
                $('.search-advanced').removeClass('hidden');
                $('.search-form form').append(advancedField);
            } else {
                $(this).text('show advanced search');
                $('.search-advanced').addClass('hidden');
                $('.field-advanced').remove();
            }
        });

        var isAdvancedVisible = {{ 'true' if advanced else 'false' }};

        var advancedField = $('.field-advanced').clone();
        $('.field-advanced').remove();
        $('.search-advanced').addClass('hidden');

        if (isAdvancedVisible) {
            $('.toggle-advanced').click();
        }
    });
</script>
{% endblock %}

app/templates/logs/results.html
{% from 'layout/macros.html' import render_pagination with context %}

{% if results.total == 0 %}
<div class="row mt-5">
    <div class="col-lg text-center">
        <div class="alert alert-info">No query logs found</div>
    </div>
</div>
{% else %}
<div class="row mt-5">
    <div class="col-lg">
        <div class="clearfix mb-3">
            <div class="float-right">
                <form action="{{ url_for('logs.export') }}/?{{ params.url() }}" method="post">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-primary">export to csv</button>
                </form>
            </div>
        </div>

        <table class="table table-sm table-striped table-responsive-lg">
            <thead>
            <tr>
                <th>#</th>
                <th>Domain</th>
                <th style="white-space: nowrap;">Source IP</th>
                <th class="text-right">Type</th>
                <th class="text-center">Forwarded</th>
                <th class="text-center">Matched</th>
                <th class="text-center">Blocked</th>
                <th class="text-right">Date</th>
                <th class="text-right"></th>
            </tr>
            </thead>
            <tbody>
            {% for result in results.items %}
                {% set is_zone = zone_exists(domain=result.domain) %}
                {% set has_alias = (result.source_ip in aliases) %}
            <tr>
                <td>{{ loop.index + (params.per_page * (params.page - 1)) }}</td>
                <td style="width: 100%">
                    {% if is_zone %}
                        <a href="{{ url_for('dns.zone_view', dns_zone_id=result.dns_zone_id) }}">{{ result.domain }}</a>
                    {% else %}
                        {{ result.domain }}
                    {% endif %}
                </td>
                <td title="{{ result.source_ip }}">{{ aliases[result.source_ip] if has_alias else result.source_ip }}</td>
                <td class="text-right">{{ result.type }}</td>
                <td class="text-center">
                    {% set class = 'success' if result.forwarded else 'danger' %}
                    {% set icon = 'check' if result.forwarded else 'times' %}
                    <span class="text-{{ class }}"><i class="fas fa-{{ icon }} fa-fw"></i></span>
                </td>
                <td class="text-center">
                    {% set class = 'success' if result.found else 'danger' %}
                    {% set icon = 'check' if result.found else 'times' %}
                    <span class="text-{{ class }}"><i class="fas fa-{{ icon }} fa-fw"></i></span>
                </td>
                <td class="text-center">
                    {% set class = 'success' if result.blocked else 'danger' %}
                    {% set icon = 'check' if result.blocked else 'times' %}
                    <span class="text-{{ class }}"><i class="fas fa-{{ icon }} fa-fw"></i></span>
                </td>
                <td class="text-right" style="white-space: nowrap;">{{ result.created_at.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                <td class="text-right" style="white-space: nowrap;">
                    <a class="btn btn-secondary btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-h"></i>
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a href="{{ url_for('logs.index', domain=result.domain) }}" class="dropdown-item"> <i class="fas fa-filter fa-fw"></i> <span class="ml-1">filter by domain</span></a>
                        <a href="{{ url_for('logs.index', source_ip=result.source_ip) }}" class="dropdown-item"> <i class="fas fa-filter fa-fw"></i> <span class="ml-1">filter by IP</span></a>

                        {% if result.dns_zone_id == 0 and is_zone == False %}
                        <form action="{{ url_for('dns.zone_create_from_log', query_log_id=result.id) }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <a href="#" class="submit-on-click dropdown-item"><i class="fas fa-plus-square fa-fw"></i> <span class="ml-1">create zone</span></a>
                        </form>
                        {% else %}
                        <a href="{{ url_for('dns.zone_view', dns_zone_id=result.dns_zone_id) }}" class="dropdown-item"><i class="fas fa-external-link-alt fa-fw"></i> <span class="ml-1">view zone</span></a>
                        {% endif %}

                        {% if not has_alias %}
                        <a href="{{ url_for('dns.alias_edit', alias_id=0, ip=result.source_ip) }}" class="dropdown-item"><i class="fas fa-plus-square fa-fw"></i> <span class="ml-1">create alias</span></a>
                        {% endif %}

                        <form action="{{ url_for('dns.zone_restriction_create_from_log', query_log_id=result.id) }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <a href="{{ url_for('dns.zone_restriction_create_from_log', query_log_id=result.id) }}" class="submit-on-click dropdown-item"><i class="fas fa-ban fa-fw"></i> <span class="ml-1">block IP</span></a>
                        </form>

                        <div class="dropdown-divider"></div>

                        <a href="#" class="dropdown-item toggle-log-response" data-id="{{ result.id }}"><i class="fas fa-glasses fa-fw"></i> <span class="ml-1">view response</span></a>
                    </div>
                </td>
            </tr>
            <tr class="d-none log-details-{{ result.id }}">
                <td></td>
                <td colspan="7">
                    {% set text = (result.data|escape).replace("\n", "<br>"|safe) %}
                    {% if text|length == 0 %}
                        No data
                    {% else %}
                        {{ text }}
                    {% endif %}
                </td>
                <td></td>
            </tr>
            <!-- Leave this to maintain the stripping -->
            <tr class="d-none">
                <td colspan="9"></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        {% if results.pages > 1 %}
            {{ render_pagination(results, url_for(page_url), params.url()) }}
        {% endif %}
    </div>
</div>
{% endif %}

<script type="text/javascript">
    $(document).ready(function() {
        $('.toggle-log-response').click(function() {
            var detailRow = $('.log-details-' + $(this).data('id'));
            if (!detailRow) {
                return false;
            }

            if ($(detailRow).hasClass('d-none')) {
                $(detailRow).removeClass('d-none');
            } else {
                $(detailRow).addClass('d-none');
            }
            return false;
        });
    });
</script>